# ?????????????????????????????????????????
# H2 - BASE DE DATOS EN MEMORIA (desarrollo)
# ?????????????????????????????????????????
# spring.datasource.url=jdbc:h2:mem:planestudios;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.jpa.defer-datasource-initialization=true

# ?????????????????????????????????????????
# JPA / HIBERNATE
# ?????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.sql.init.mode=never
logging.level.org.hibernate.SQL=INFO

# ?????????????????????????????????????????
# POSTGRESQL (Supabase)
# ?????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.rwagpkjuwjurgvisrirs
spring.datasource.password=Mierda2404Hola
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?????????????????????????????????????????
# JWT
# ?????????????????????????????????????????
jwt.secret=clave-secreta-super-larga-cambiar-en-produccion-minimo-256-bits
jwt.expiration=86400000

# ?????????????????????????????????????????
# CORS
# ?????????????????????????????????????????
cors.allowed-origins=http://localhost:5173

# ?????????????????????????????????????????
# SERVER
# ?????????????????????????????????????????
server.port=8080