-- Materias
INSERT INTO materias (codigo, nombre, anio) VALUES ('am1', 'Análisis Matemático I', 1);
INSERT INTO materias (codigo, nombre, anio) VALUES ('alg', 'Álgebra y Geometría', 1);
INSERT INTO materias (codigo, nombre, anio) VALUES ('intro', 'Intro a la Programación', 1);
INSERT INTO materias (codigo, nombre, anio) VALUES ('fis1', 'Física I', 1);
INSERT INTO materias (codigo, nombre, anio) VALUES ('arq1', 'Organización del Computador', 1);
INSERT INTO materias (codigo, nombre, anio) VALUES ('am2', 'Análisis Matemático II', 2);
INSERT INTO materias (codigo, nombre, anio) VALUES ('prog2', 'Programación II', 2);
INSERT INTO materias (codigo, nombre, anio) VALUES ('discreta', 'Matemática Discreta', 2);
INSERT INTO materias (codigo, nombre, anio) VALUES ('fis2', 'Física II', 2);
INSERT INTO materias (codigo, nombre, anio) VALUES ('arq2', 'Arquitectura de Computadoras', 2);
INSERT INTO materias (codigo, nombre, anio) VALUES ('algo3', 'Algoritmos y Estructuras', 3);
INSERT INTO materias (codigo, nombre, anio) VALUES ('prob', 'Probabilidad y Estadística', 3);
INSERT INTO materias (codigo, nombre, anio) VALUES ('sis', 'Sistemas Operativos', 3);
INSERT INTO materias (codigo, nombre, anio) VALUES ('redes', 'Redes de Computadoras', 3);
INSERT INTO materias (codigo, nombre, anio) VALUES ('bd', 'Bases de Datos', 3);
INSERT INTO materias (codigo, nombre, anio) VALUES ('ia', 'Inteligencia Artificial', 4);
INSERT INTO materias (codigo, nombre, anio) VALUES ('distrib', 'Sistemas Distribuidos', 4);
INSERT INTO materias (codigo, nombre, anio) VALUES ('ing', 'Ingeniería de Software', 4);
INSERT INTO materias (codigo, nombre, anio) VALUES ('seg', 'Seguridad Informática', 4);
INSERT INTO materias (codigo, nombre, anio) VALUES ('comp', 'Compiladores', 4);
INSERT INTO materias (codigo, nombre, anio) VALUES ('ml', 'Machine Learning', 5);
INSERT INTO materias (codigo, nombre, anio) VALUES ('pf', 'Proyecto Final', 5);
INSERT INTO materias (codigo, nombre, anio) VALUES ('tesis', 'Tesis de Grado', 5);
INSERT INTO materias (codigo, nombre, anio) VALUES ('elec1', 'Electiva I', 5);
INSERT INTO materias (codigo, nombre, anio) VALUES ('elec2', 'Electiva II', 5);

-- Correlativas (usando subquery para obtener el id)
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'am2'), 'am1');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'am2'), 'alg');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'prog2'), 'intro');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'discreta'), 'alg');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'fis2'), 'fis1');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'fis2'), 'am1');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'arq2'), 'arq1');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'arq2'), 'intro');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'algo3'), 'prog2');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'algo3'), 'discreta');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'prob'), 'am2');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'sis'), 'arq2');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'sis'), 'prog2');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'redes'), 'sis');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'bd'), 'prog2');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'bd'), 'discreta');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ia'), 'algo3');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ia'), 'prob');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'distrib'), 'sis');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'distrib'), 'redes');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ing'), 'algo3');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ing'), 'bd');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'seg'), 'redes');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'seg'), 'sis');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'comp'), 'algo3');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ml'), 'ia');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'ml'), 'prob');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'pf'), 'ing');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'pf'), 'distrib');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'tesis'), 'pf');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'elec1'), 'ia');
INSERT INTO correlativas (materias_id, correlativa_codigo) VALUES ((SELECT id FROM materias WHERE codigo = 'elec2'), 'ing');
